export const ALL_BUILDING_REQUEST="ALL_BUILDING_REQUEST";
export const ALL_BUILDING_SUCCESS="ALL_BUILDING_SUCCESS";
export const ALL_BUILDING_FAIL="ALL_BUILDING_FAIL";


export const ALL_ROOM_REQUEST="ALL_ROOM_REQUEST";
export const ALL_ROOM_SUCCESS="ALL_ROOM_SUCCESS";
export const ALL_ROOM_FAIL="ALL_ROOM_FAIL";


export const ALL_ROOM_VIEW_REQUEST="ALL_ROOM_VIEW_REQUEST";
export const ALL_ROOM_VIEW_SUCCESS="ALL_ROOM_VIEW_SUCCESS";
export const ALL_ROOM_VIEW_FAIL="ALL_ROOM_VIEW_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";

