export const ALL_SUMMARY_HOME_REQUEST="ALL_SUMMARY_HOME_REQUEST";
export const ALL_SUMMARY_HOME_SUCCESS="ALL_SUMMARY_HOME_SUCCESS";
export const ALL_SUMMARY_HOME_FAIL="ALL_SUMMARY_HOME_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";
