export const ALL_USER_REQUEST="ALL_USER_REQUEST";
export const ALL_USER_SUCCESS="ALL_USER_SUCCESS";
export const ALL_USER_FAIL="ALL_USER_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS";


export const ALL_USER_VIEW_REQUEST="ALL_USER_VIEW_REQUEST";
export const ALL_USER_VIEW_SUCCESS="ALL_USER_VIEW_SUCCESS";
export const ALL_USER_VIEW_FAIL="ALL_USER_VIEW_FAIL";